[package]
name = "aar"
version = "0.2.0"
authors = ["Markus Stensiö <markus.stensio@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]


[dependencies]
ux = "0.1"
log = "0.4"
env_logger = "0.8"
# dexparser = "0.6"
dexparser = { git="https://github.com/maekoos/dexparser.git" }